#version 460

#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 8, local_size_y = 8) in;

layout(std430, binding = 0) readonly buffer Framebuffer {
    uint64_t pixels[];
};

// r = depth
// g = shading term
layout(std430, binding = 1) readonly buffer EdlLevelInfo {
    vec2 edl[];
};

layout(binding = 0, rgba8) writeonly uniform image2D outputTexture;

uniform ivec2 framebufferSize;
uniform bool useEdl;
uniform float edlShadingStrength;

void main() {
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    if (texel.x >= framebufferSize.x || texel.y >= framebufferSize.y) {
        return;
    }

    uint index = uint(texel.x + texel.y * framebufferSize.x);
    uint64_t pixel = pixels[index];

    uint rgb = uint(pixel & 0xffffffu);
    vec4 color = vec4(
        ((rgb >> 16) & 0xffu) / 255.0f,
        ((rgb >> 8) & 0xffu) / 255.0f,
        (rgb & 0xffu) / 255.0f,
        1.0f
    );

    if (useEdl) {
        float shadingTerm = exp(-edl[index].g * edlShadingStrength);
        color = shadingTerm * color;
    }

    imageStore(outputTexture, texel, color);
}
