#version 460

#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 8, local_size_y = 8) in;

layout(std430, binding = 0) readonly buffer SourceFramebuffer {
    uint64_t source[];
};

layout(std430, binding = 1) writeonly buffer DestinationFramebuffer {
    uint64_t destination[];
};

layout(std430, binding = 2) buffer EmptyPixels {
    uint empty[];
};

uniform ivec2 framebufferSize;
uniform int iteration;
uniform float influence;

bool is_pixel_empty(uint64_t pixel) {
    // Check if depth is valid
    return (pixel >> 32) == 0xfffffffful;
}

void bubble_sort(inout uint64_t values[9], uint count) {
    for (int i = 0; i < count; i++) {
        bool sorted = true;

        for (int j = 0; j < count - 1 - i; j++) {
            if (values[j] > values[j + 1]) {
                uint64_t temp = values[j];
                values[j] = values[j + 1];
                values[j + 1] = temp;

                sorted = false;
            }
        }

        if (sorted) return;
    }
}

uint64_t median(uint64_t values[9], uint count) {
    bubble_sort(values, count);

    if (count % 2 == 0) {
        return (values[count / 2 - 1] + values[count / 2]) / 2;
    } else {
        return values[count / 2];
    }
}

void main() {
    ivec2 position = ivec2(gl_GlobalInvocationID.xy);
    if (position.x >= framebufferSize.x || position.y >= framebufferSize.y) {
        return;
    }

    uint index = uint(position.x + position.y * framebufferSize.x);
    uint64_t pixel = source[index];

    // Gather all empty (invalid) pixels
    if (iteration == 0) {
        empty[index] = is_pixel_empty(pixel) ? 1 : 0;
        destination[index] = pixel;
        return;
    }

    // Skip non-empty pixels
    if (empty[index] == 0) {
        destination[index] = pixel;
        return;
    }

    if (is_pixel_empty(pixel)) {
        // Pixel was initially empty and still is
        // Calculate depth median of a 3x3 neighborhood
        uint64_t neighborhood[9];
        int count = 0;

        for(int j = -1; j <= 1; j++) {
            for(int i = -1; i <= 1; i++) {
                ivec2 neighborPosition = clamp(position + ivec2(i, j), ivec2(0), framebufferSize - 1);
                uint neighborIndex = uint(neighborPosition.x + neighborPosition.y * framebufferSize.x);
                uint64_t neighbor = source[neighborIndex];

                if (!is_pixel_empty(neighbor))
                    neighborhood[count++] = neighbor;
            }
        }

        // Because depth is in the highest 32 bits it is possible to disregard rgb
        if (count != 0) { 
            destination[index] = median(neighborhood, count);
            return;
        }
    } else {
        // Pixel was initially empty but now it has a valid depth
        // Update depth and color based on a 3x3 neighborhood

        // Depth is in range [0, 1]
        float depth = float(source[index] >> 32) / 4294967295.0f;

        float depthSum = 0.0f;
        float rSum = 0.0f;
        float gSum = 0.0f;
        float bSum = 0.0f;
        float weightSum = 0.0f;

        for (int j = -1; j <= 1; j++) {
            for (int i = -1; i <= 1; i++) {
                ivec2 neighborPosition = clamp(position + ivec2(i, j), ivec2(0), framebufferSize - 1);
                uint64_t neighbor = source[neighborPosition.x + neighborPosition.y * framebufferSize.x];

                if (is_pixel_empty(neighbor)) {
                    continue;
                }

                // Depth is in range [0, 1]
                float neighborDepth = float(neighbor >> 32) / 4294967295.0f;
                float neighborR = float((neighbor >> 16) & 0xff);
                float neighborG = float((neighbor >> 8) & 0xff);
                float neighborB = float(neighbor & 0xff);

                float weight = (1.0f - length(vec2(i, j)) / 2.0f) * (1.0f - min(1.0f, abs(neighborDepth - depth) / influence));
                depthSum += weight * neighborDepth;
                rSum += weight * neighborR;
                gSum += weight * neighborG;
                bSum += weight * neighborB;
                weightSum += weight;
            }
        }

        if (weightSum > 0.0f) {
            uint64_t d = uint64_t(clamp(depthSum / weightSum, 0.0f, 1.0f) * 4294967295.0f);
            uint64_t r = uint64_t(rSum / weightSum);
            uint64_t g = uint64_t(gSum / weightSum);
            uint64_t b = uint64_t(bSum / weightSum);

            destination[index] = (d << 32) | (r << 16) | (g << 8) | b;
            return;
        }
    }
    
    destination[index] = pixel;
}
