#version 460

#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_EXT_shader_atomic_int64 : enable

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer Points {
    vec4 positions[];
};

layout(std430, binding = 1) buffer Framebuffer {
    uint64_t pixels[];
};

uniform mat4 mvp;
uniform ivec2 framebufferSize;
uniform uint color;

uint toPixelId(vec4 clip) {
    vec3 ndc = clip.xyz / clip.w;
    ivec2 screen = ivec2(
        (ndc.x * 0.5 + 0.5) * framebufferSize.x,
        (ndc.y * 0.5 + 0.5) * framebufferSize.y
    );

    if (screen.x < 0 || screen.y < 0 || screen.x >= framebufferSize.x || screen.y >= framebufferSize.y) {
        return uint(-1);
    }

    return uint(screen.x + screen.y * framebufferSize.x);
}

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= positions.length()) {
        return;
    }

    vec4 clip = mvp * positions[id];
    // Near plane clipping
    if (clip.w <= 0.0f) {
        return; 
    }

    uint pixelId = toPixelId(clip);
    if (pixelId == uint(-1)) {
        return;
    }

    // TODO: NDC depth is not linear
    float depthNdc = clip.z / clip.w;
    float depth01 = clamp(depthNdc * 0.5 + 0.5, 0.0f, 1.0f);
    // 2^32 - 1 = 4294967295
    uint64_t depth = uint64_t(depth01 * 4294967295.0f);
    uint64_t point = (uint64_t(depth) << 32) | (uint64_t(color & 0xffffffu));
    atomicMin(pixels[pixelId], point);
}
