#version 460

#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 8, local_size_y = 8) in;

layout(std430, binding = 0) readonly buffer Framebuffer {
    uint64_t pixels[];
};

layout(binding = 0, rgba8) writeonly uniform image2D outputTexture;

uniform ivec2 framebufferSize;

void main() {
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    if (texel.x >= framebufferSize.x || texel.y >= framebufferSize.y) {
        return;
    }

    uint index = uint(texel.x + texel.y * framebufferSize.x);
    uint64_t pixel = pixels[index];

    uint rgb = uint(pixel & 0xffffffu);
    vec4 color = vec4(
        ((rgb >> 16) & 0xffu) / 255.f,
        ((rgb >> 8) & 0xffu) / 255.f,
        (rgb & 0xffu) / 255.f,
        1.f
    );

    imageStore(outputTexture, texel, color);
}
