#version 460

#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_EXT_shader_atomic_int64 : enable

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer Points {
    vec4 positions[];
};

layout(std430, binding = 1) buffer Framebuffer {
    uint64_t pixels[];
};

layout(std430, binding = 2) buffer Depth {
    uint depths[];
};

layout(std430, binding = 3) buffer Fallback {
    uint64_t fallback[];
};

uniform mat4 mvp;
uniform ivec2 framebufferSize;

uint toPixelId(vec4 clip) {
    vec3 ndc = clip.xyz / clip.w;
    ivec2 screen = ivec2(
        (ndc.x * 0.5 + 0.5) * framebufferSize.x,
        (ndc.y * 0.5 + 0.5) * framebufferSize.y
    );

    if (screen.x < 0 || screen.y < 0 || screen.x >= framebufferSize.x || screen.y >= framebufferSize.y) {
        return uint(-1);
    }

    return uint(screen.x + screen.y * framebufferSize.x);
}

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= positions.length()) {
        return;
    }

    vec4 clip = mvp * positions[id];
    // Near plane clipping
    if (clip.w <= 0.f) {
        return; 
    }

    uint pixelId = toPixelId(clip);
    if (pixelId == uint(-1)) {
        return;
    }

    float bufferDepth = uintBitsToFloat(depths[pixelId]);
    if (clip.w > bufferDepth * 1.01) {
        return;
    }

    uint64_t red = 0;
    uint64_t green = 0;
    uint64_t blue = 255;

    uint64_t rgba = (red << 48) | (green << 32) | (blue << 16) | 1;
    uint64_t old = atomicAdd(pixels[pixelId], rgba);
    uint count = uint(old & 0xffff);

    if (count >= 255) {
        int counter = 1;

        if (count == 255) {
            atomicExchange(pixels[pixelId], 0);

            red += (old >> 48) & 0xffff;
            green += (old >> 32) & 0xffff;
            blue += (old >> 16) & 0xffff;
            counter += 255;
        }

        uint64_t rg = (red << 32) | green;
        uint64_t ba = (blue << 32) | counter;

        atomicAdd(fallback[2 * pixelId], rg);
        atomicAdd(fallback[2 * pixelId + 1], ba);
    }
}
