#version 460

#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_EXT_shader_atomic_int64 : enable

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer Points {
    vec4 positions[];
};

layout(std430, binding = 1) readonly buffer Colors {
    uint colors[];
};

layout(std430, binding = 2) buffer Framebuffer {
    uint64_t pixels[];
};

layout(std430, binding = 3) readonly buffer Depth {
    uint depths[];
};

layout(std430, binding = 4) buffer Fallback {
    uint64_t fallback[];
};

uniform mat4 mvp;
uniform ivec2 framebufferSize;
uniform bool useDefaultColor;
uniform uint64_t defaultColor;
uniform uint vertexOffset;
uniform uint vertexCount;

uint toPixelId(vec4 clip) {
    vec3 ndc = clip.xyz / clip.w;
    ivec2 screen = ivec2(
        (ndc.x * 0.5f + 0.5f) * framebufferSize.x,
        (ndc.y * 0.5f + 0.5f) * framebufferSize.y
    );

    if (screen.x < 0 || screen.y < 0 || screen.x >= framebufferSize.x || screen.y >= framebufferSize.y) {
        return uint(-1);
    }

    return uint(screen.x + screen.y * framebufferSize.x);
}

void main() {
    // Id in octree node
    uint id = gl_GlobalInvocationID.x;
    if (id >= vertexCount) {
        return;
    }

    // Id in global SSBO
    id += vertexOffset;
    if (id >= positions.length()) {
        return;
    }

    vec4 clip = mvp * positions[id];
    // Near plane clipping
    if (clip.w <= 0.0f) {
        return; 
    }

    uint pixelId = toPixelId(clip);
    if (pixelId == uint(-1)) {
        return;
    }

    // Convert uint depth to float in range [0, 1]
    // TODO: NDC depth is not linear
    float bufferDepth = float(depths[pixelId]) / 4294967295.0f;
    float pixelDepth = clamp((clip.z / clip.w) * 0.5f + 0.5f, 0.0f, 1.0f);
    if (pixelDepth > bufferDepth * 1.01f) {
        return;
    }

    uint64_t red = (defaultColor & 0x0000ffff00000000ul) >> 32;
    uint64_t green = (defaultColor & 0x00000000ffff0000ul) >> 16;
    uint64_t blue = defaultColor & 0x00000000fffful;
    if (!useDefaultColor) {
        vec4 c = unpackUnorm4x8(colors[id]);

        red = uint64_t(c.r * 255.0f);
        green = uint64_t(c.g * 255.0f);
        blue = uint64_t(c.b * 255.0f);
    }

    uint64_t rgba = (red << 48) | (green << 32) | (blue << 16) | 1;
    uint64_t old = atomicAdd(pixels[pixelId], rgba);
    uint count = uint(old & 0xffff);

    if (count >= 255) {
        int counter = 1;

        if (count == 255) {
            atomicExchange(pixels[pixelId], 0);

            red += (old >> 48) & 0xffff;
            green += (old >> 32) & 0xffff;
            blue += (old >> 16) & 0xffff;
            counter += 255;
        }

        uint64_t rg = (red << 32) | green;
        uint64_t ba = (blue << 32) | counter;

        atomicAdd(fallback[2 * pixelId], rg);
        atomicAdd(fallback[2 * pixelId + 1], ba);
    }
}
