#version 460

#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 8, local_size_y = 8) in;

layout(std430, binding = 0) readonly buffer Framebuffer {
    uint64_t pixels[];
};

layout(std430, binding = 1) readonly buffer Fallback {
    uint64_t fallback[];
};

layout(binding = 0, rgba8) writeonly uniform image2D outputTexture;

uniform ivec2 framebufferSize;

void main() {
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    if (texel.x >= framebufferSize.x || texel.y >= framebufferSize.y) {
        return;
    }

    uint pixelId = uint(texel.x + texel.y * framebufferSize.x);
    uint64_t rgba = pixels[pixelId];

    // Accumulate from framebuffer
    uint r = uint((rgba >> 48) & 0xffff);
    uint g = uint((rgba >> 32) & 0xffff);
    uint b = uint((rgba >> 16) & 0xffff);
    uint a = uint(rgba & 0xffff);

    uint64_t rgFallback = fallback[2 * pixelId];
    uint64_t baFallback = fallback[2 * pixelId + 1];

    // Accumulate from fallback
    r += uint(rgFallback >> 32);
    g += uint(rgFallback & 0xffffffff);
    b += uint(baFallback >> 32);
    a += uint(baFallback & 0xffffffff);

    if (a == 0) {
        imageStore(outputTexture, texel, vec4(0.0f, 0.0f, 0.0f, 1.0f));
    } else {
        vec4 color = vec4(
            float(r) / float(a) / 255.0f,
            float(g) / float(a) / 255.0f,
            float(b) / float(a) / 255.0f,
            1.0f
        );

        imageStore(outputTexture, texel, color);
    }
}
