#version 460

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer Points {
    vec4 positions[];
};

layout(std430, binding = 1) buffer Depth {
    uint depths[];
};

uniform mat4 mvp;
uniform ivec2 framebufferSize;

uint toPixelId(vec4 clip) {
    vec3 ndc = clip.xyz / clip.w;
    ivec2 screen = ivec2(
        (ndc.x * 0.5 + 0.5) * framebufferSize.x,
        (ndc.y * 0.5 + 0.5) * framebufferSize.y
    );

    if (screen.x < 0 || screen.y < 0 || screen.x >= framebufferSize.x || screen.y >= framebufferSize.y) {
        return uint(-1);
    }

    return uint(screen.x + screen.y * framebufferSize.x);
}

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= positions.length()) {
        return;
    }

    vec4 clip = mvp * positions[id];
    // Near plane clipping
    if (clip.w <= 0.f) {
        return; 
    }

    uint pixelId = toPixelId(clip);
    if (pixelId == uint(-1)) {
        return;
    }

    uint depth = floatBitsToUint(clip.w);
    atomicMin(depths[pixelId], depth);
}
