#version 460

#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 8, local_size_y = 8) in;

// r = depth
// g = shading term
layout(std430, binding = 0) readonly buffer EdlLevelInfo {
    vec2 edl[];
};

layout(binding = 0, rgba8) uniform image2D outputTexture;

uniform ivec2 framebufferSize;
uniform bool useEdl;
uniform float edlShadingStrength;

void main() {
    ivec2 position = ivec2(gl_GlobalInvocationID.xy);
    if (position.x >= framebufferSize.x || position.y >= framebufferSize.y) {
        return;
    }

    uint index = uint(position.x + position.y * framebufferSize.x);
    vec4 color = imageLoad(outputTexture, position);

    if (useEdl) {
        float shadingTerm = exp(-edl[index].g * edlShadingStrength);
        color = shadingTerm * color;
    }

    imageStore(outputTexture, position, color);
}
